#!/usr/bin/ruby -w

gem 'ruby-cute', ">=0.6"
require 'cute'
require 'pp'


# Run a command on each node and analyze result
ssh = Net::SSH::Multi::Session::new
@hostname = "granduc-5.luxembourg.grid5000.fr"
@username = "root"
@password = ""
@cmd = "wget https://raw.githubusercontent.com/snt-sedan/Blockchain-Testbed/master/Blockchain/ethereum/GenerateStaticNode.sh"
@cmd2= "chmod u+x GenerateStaticNode.sh"
@cmd3= "./GenerateStaticNode.sh"

 begin
    ssh = Net::SSH.start(@hostname, @username, :password => @password)
    ssh.exec!(@cmd)
    ssh.exec!(@cmd2)
    res = ssh.exec!(@cmd3)
    puts res
    output = File.open( "static-nodes.json","w" )
    output << res
    output.close
    ssh.close

  rescue
    puts "Unable to connect to #{@hostname} using #{@username}/#{@password}"
  end
